export enum tagTypes {
  profile = 'profile',
  engagement = 'engagement',
  socialMedia = 'socialMedia',
  country = 'country',
  privacy = 'privacy',
  terams = 'terms',
  a_reviewer = 'a_reviewer',
  a_sin_reviewer = 'a_sin_reviewer',
  a_financial = 'a_financial',
  a_support = 'a_support',
  a_support_dts = 'a_support_dts',
  a_admin = 'a_admin',
  a_performance = 'a_performance',
  a_media = 'a_media',
}

export const tagTypesList = [
  tagTypes.profile,
  tagTypes.engagement,
  tagTypes.socialMedia,
  tagTypes.country,
  tagTypes.a_reviewer,
  tagTypes.a_sin_reviewer,
  tagTypes.a_financial,
  tagTypes.a_support,
  tagTypes.a_support_dts,
  tagTypes.a_admin,
  tagTypes.privacy,
  tagTypes.terams,
  tagTypes.a_performance,
  tagTypes.a_media,
];
