export enum tagTypes {
  profile = 'profile',
  engagement = 'engagement',
  socialMedia = 'socialMedia',
  country = 'country',
  privacy = 'privacy',
  terams = 'terms',
  a_reviewer = 'a_reviewer',
  a_sin_reviewer = 'a_sin_reviewer',
  a_financial = 'a_financial',
  a_support = 'a_support',
  a_support_dts = 'a_support_dts',
  a_admin = 'a_admin',
  a_performance = 'a_performance',
  a_media = 'a_media',
  a_user = 'a_user',
  a_single_user = 'a_single_user',
  a_admin_overview = 'a_admin_overview',
  a_notification = 'a_notification',
  r_dashboard = 'r_dashboard',
  r_account = 'r_account',
  r_task = 'r_task',
  r_support = 'r_support',
  r_perform = 'r_perform',
}

export const tagTypesList = [
  tagTypes.profile,
  tagTypes.engagement,
  tagTypes.socialMedia,
  tagTypes.country,
  tagTypes.a_reviewer,
  tagTypes.a_sin_reviewer,
  tagTypes.a_financial,
  tagTypes.a_support,
  tagTypes.a_support_dts,
  tagTypes.a_admin,
  tagTypes.privacy,
  tagTypes.terams,
  tagTypes.a_performance,
  tagTypes.a_media,
  tagTypes.a_user,
  tagTypes.a_single_user,
  tagTypes.a_admin_overview,
  tagTypes.a_notification,
  tagTypes.r_dashboard,
  tagTypes.r_account,
  tagTypes.r_task,
  tagTypes.r_support,
  tagTypes.r_perform,
];
