export const reviewerlinks = [
  {
    label: 'Dashboard',
    icon: 'overview',
    active_i: 'overview_active2',
    color: '#ffffff',
    bg: '#FD7701',
    to: '/reviewer',
  },
  {
    label: 'Account Verification',
    icon: 'account',
    active_i: 'account_active',
    color: '#ffffff',
    bg: '#FD7701',
    to: '/reviewer/account-verification',
  },
  {
    label: 'Task Review',
    icon: 'task',
    active_i: 'task_active',
    color: '#ffffff',
    bg: '#FD7701',
    to: '/reviewer/task-review',
  },
  {
    label: 'Performance Review',
    icon: 'performance',
    active_i: 'performance_active',
    color: '#ffffff',
    bg: '#FD7701',
    to: '/reviewer/performance-review',
  },
  {
    label: 'Support',
    icon: 'support',
    active_i: 'support_active',
    color: '#ffffff',
    bg: '#FD7701',
    to: '/reviewer/support',
  },
];

// adminlinks
export const adminLinks = [
  {
    label: 'Dashboard',
    icon: 'overview',
    active_i: 'overview_active',
    color: '#fd7701',
    bg: 'rgba(96, 96, 96, 0.20)',
    to: '/admin',
  },
  {
    label: 'User Management',
    icon: 'user_manage',
    active_i: 'user_manage_acive',
    color: '#fd7701',
    bg: 'rgba(96, 96, 96, 0.20)',
    to: '/admin/user-management',
  },
  {
    label: 'Reviewer Management',
    icon: 'reviewer_manage',
    active_i: 'reviewer_manage_active',
    color: '#fd7701',
    bg: 'rgba(96, 96, 96, 0.20)',
    to: '/admin/reviewer-management',
  },
  {
    label: 'Task & Order Management',
    icon: 'task_order_manage',
    active_i: 'task_order_manage_active',
    color: '#fd7701',
    bg: 'rgba(96, 96, 96, 0.20)',
    to: '/admin/task-order',
  },
  {
    label: 'Engagement Management',
    icon: 'engagement_manage',
    active_i: 'engagement_manage_active',
    color: '#fd7701',
    bg: 'rgba(96, 96, 96, 0.20)',
    to: '/admin/engagement-management',
  },
  {
    label: 'Content & Media Control',
    icon: 'cut',
    active_i: 'cut_active',
    color: '#fd7701',
    bg: 'rgba(96, 96, 96, 0.20)',
    to: '/admin/media-control',
  },
  {
    label: 'Performance & Analytics',
    icon: 'perfomace',
    active_i: 'perfomace_active',
    color: '#fd7701',
    bg: 'rgba(96, 96, 96, 0.20)',
    to: '/admin/performance-analytics',
  },
  {
    label: 'Support & Disputes',
    icon: 'support_dispute',
    active_i: 'support_dispute_active',
    color: '#fd7701',
    bg: 'rgba(96, 96, 96, 0.20)',
    to: '/admin/support-disputes',
  },
  {
    label: 'Financial Controls',
    icon: 'financial_controls',
    active_i: 'financial_controls_active',
    color: '#fd7701',
    bg: 'rgba(96, 96, 96, 0.20)',
    to: '/admin/financial-controls',
  },
  {
    label: 'System Settings',
    icon: 'system_settings',
    active_i: 'system_settings_active',
    color: '#fd7701',
    bg: 'rgba(96, 96, 96, 0.20)',
    to: '/admin/system-settings',
  },
  {
    label: 'Communication Tools',
    icon: 'communication',
    active_i: 'communication_active',
    color: '#fd7701',
    bg: 'rgba(96, 96, 96, 0.20)',
    to: '/admin/communication',
  },
];

//   export const adminLinks = [
//     { to: "/company", icon: LayoutDashboard, label: "Dashboard" },
//     { to: "/company/settings", icon: Dock, label: "Company Settings" },
//     { to: "/company/providers", icon: House, label: "Service providers" },
//     { to: "/company/bookings", icon: Dock, label: "Bookings" },
//     { to: "/company/chats", icon: MessageSquare, label: "Chats" },
//     { to: "/company/feedbacks", icon: ThumbsUp, label: "Feedbacks" },
//     {
//       icon: Settings,
//       label: "Settings",
//       submenu: [
//         { to: "/company/change-password", icon: KeyRound, label: "Change Password" },
//       ],
//     },
//   ];
